const ensemblePages = {
  voxpueri:{name:"VoxPueri",range:"4–9/10 anos",tag:"Coro infantil · Cascais",image:"../assets/ensembles/voxpueri.jpg",lead:"A primeira aventura coral: voz, movimento, ocarina, escuta e descoberta.",schedule:"Segunda-feira · 17h–17h50",description:"VoxPueri oferece às crianças uma primeira experiência musical em grupo. O canto, o movimento e os instrumentos simples ajudam a desenvolver ouvido, coordenação, linguagem, autonomia e confiança.",benefits:[["Descoberta","Aprender música através do jogo, do corpo, da voz e da curiosidade."],["Confiança","Cantar com outras crianças ajuda a comunicar, escutar e subir ao palco com segurança."],["Comunidade","Uma experiência artística que aproxima crianças, famílias e novas amizades."]]},
  voxsoul:{name:"VoxSoul",range:"10–18 anos",tag:"Coro juvenil · Cascais",image:"../assets/ensembles/voxsoul.jpg",lead:"Identidade, técnica vocal, palco, amizade e mundo.",schedule:"Segundas e quartas · 18h–19h15",description:"VoxSoul é o coro juvenil da comunidade VoxLaci. Dois ensaios semanais permitem aprofundar técnica vocal, harmonia, repertório e presença em palco, ao mesmo tempo que criam pertença e relações duradouras.",benefits:[["Autoestima","Partilhar a própria voz ajuda cada jovem a sentir-se valorizado e ouvido."],["Evolução vocal","Respiração, afinação, controlo da voz e canto em harmonia."],["Palco e viagens","Oportunidades de atuar em Portugal e no estrangeiro, conhecer culturas e criar memórias."]]},
  voxatma:{name:"VoxAtma",range:"Adultos",tag:"Coro de adultos · Cascais",image:"../assets/ensembles/voxatma.jpg",lead:"Respirar, reencontrar a voz e transformar.",schedule:"Segunda-feira · 20h15–21h30",description:"VoxAtma acolhe adultos com ou sem experiência musical. É um espaço para trabalhar a voz, cantar repertório variado, reduzir o stress e transformar a experiência individual através de uma prática artística regular.",benefits:[["Bem-estar","A respiração e o canto coletivo criam foco, energia e equilíbrio."],["Aprendizagem","Não é necessário saber ler música: o percurso é acompanhado passo a passo."],["Transformação","Um grupo onde cada voz contribui para transformar o som e a comunidade."]]},
  voxcor:{name:"VoxCor",range:"Adultos",tag:"Coro adulto · Grupo vocal",image:"../assets/ensembles/voxcor.jpg",lead:"Repertório coral, compromisso artístico e comunidade.",schedule:"Horário mediante temporada",description:"VoxCor reúne vozes adultas num trabalho coral de repertório, técnica, interpretação e palco. A experiência combina exigência musical com o espírito de comunidade que define VoxLaci.",benefits:[["Repertório","Obras de diferentes épocas, estilos e geografias."],["Interpretação","Trabalho de frase, texto, som de conjunto e presença cénica."],["Concertos","Participação em projetos, festivais e concertos da comunidade."]]},
  tutti:{name:"Tutti",range:"Todas as vozes",tag:"Cantar coletivo · Cantar em grupo",image:"../assets/ensembles/tutti.jpg",lead:"Um grupo próprio para cantar, ligar pessoas e construir comunidade.",schedule:"Horário mediante projeto",description:"Tutti é cantar coletivo em estado puro: um espaço acessível onde a experiência de grupo, a escuta e a alegria de fazer música em conjunto são o centro.",benefits:[["Acolhimento","Um ponto de entrada para quem quer voltar a cantar ou começar."],["Ligação","A música como forma de conhecer pessoas e criar relações."],["Expressão","Descobrir possibilidades da voz sem pressão ou rótulos."]]},
  intuicao:{name:"Intuição",range:"Vozes femininas",tag:"Ensemble vocal",image:"../assets/ensembles/intuicao.jpg",lead:"A cor, a força e a intimidade das vozes femininas.",schedule:"Por audição e projeto",description:"Intuição explora repertório escrito e adaptado para vozes femininas, com atenção à fusão sonora, independência vocal e interpretação.",benefits:[["Som","Equilíbrio, afinação e identidade tímbrica."],["Repertório","Música coral feminina de diferentes tradições."],["Ensemble","Trabalho próximo e exigente entre cantoras."]]},
  hirmandade:{name:"Hirmandade",range:"Vozes masculinas · 15+",tag:"Ensemble vocal masculino",image:"../assets/ensembles/hirmandade.jpg",lead:"Fraternidade, presença e repertório para vozes masculinas.",schedule:"Segundas-feiras · 20h30–23h",description:"Hirmandade reúne cantores masculinos com mais de 15 anos num ensemble dedicado à técnica, repertório e construção de um som comum.",benefits:[["Fraternidade","Um ensemble onde a relação humana sustenta o trabalho musical."],["Técnica","Desenvolvimento das diferentes tessituras masculinas."],["Palco","Projetos e atuações com identidade própria."]]},
  kyma:{name:"KYMA",range:"Avançado",tag:"Vocal Ensemble Pro",image:"../assets/ensembles/kyma.webp",lead:"Onda, movimento e criação vocal de elevada exigência.",schedule:"Por audição ou convite",description:"KYMA é o percurso de orientação profissional da VoxLaci, criado para cantores com preparação sólida e disponibilidade para projetos de maior exigência.",benefits:[["Excelência","Preparação individual e rigor de ensemble."],["Criação","Repertório desafiante e novas linguagens vocais."],["Projeção","Projetos orientados para contextos profissionais."]]},
  quorum:{name:"Qūórum",range:"Coro de câmara",tag:"Chamber Choir",image:"../assets/ensembles/quorum.jpg",lead:"Precisão, escuta e repertório de câmara.",schedule:"Por audição",description:"Qūórum é um coro de câmara para cantores com experiência, orientado para repertório que exige autonomia, leitura, afinação e grande qualidade de conjunto.",benefits:[["Câmara","Poucas vozes, grande responsabilidade individual."],["Precisão","Afinação, equilíbrio, dicção e estilo."],["Repertório","Programas de elevada densidade artística."]]},
  voxpetrus:{name:"Vox Petrus",range:"Litúrgico",tag:"Cerimónias · Música sacra",image:"../assets/ensembles/voxpetrus.jpg",lead:"Música litúrgica para celebrações e momentos de significado.",schedule:"Por cerimónia ou projeto",description:"Vox Petrus reúne repertório e formações adequadas a missas, casamentos, baptizados, homenagens e outros contextos litúrgicos.",benefits:[["Repertório sacro","Seleção musical adequada a cada celebração."],["Formações","Soluções vocais e instrumentais adaptadas ao espaço."],["Acompanhamento","Preparação do programa em diálogo com cada família ou organização."]]}
};
const ensembleEnglish = {
  voxpueri:{range:"Ages 4–9/10",tag:"Children's choir · Cascais",lead:"A first choral adventure: voice, movement, ocarina, listening and discovery.",schedule:"Monday · 5pm–5:50pm",description:"VoxPueri gives children a first musical experience in a group. Singing, movement and simple instruments develop listening, coordination, language, independence and confidence.",benefits:[["Discovery","Learning music through play, body, voice and curiosity."],["Confidence","Singing with other children develops communication, listening and stage confidence."],["Transformation","An artistic experience that transforms children, families and new friendships."]]},
  voxsoul:{range:"Ages 10–18",tag:"Youth choir · Cascais",lead:"Identity, vocal technique, stage, friendship and world.",schedule:"Monday and Wednesday · 6pm–7:15pm",description:"VoxSoul is VoxLaci's youth choir. Two weekly rehearsals deepen vocal technique, harmony, repertoire and stage presence while building belonging and lasting relationships.",benefits:[["Self-esteem","Sharing one's voice helps every young person feel valued and heard."],["Vocal growth","Breathing, tuning, vocal control and singing in harmony."],["Stage and travel","Opportunities to perform in Portugal and abroad, discover cultures and create memories."]]},
  voxatma:{range:"Adults",tag:"Adult choir · Cascais",lead:"Breathe, reconnect with your voice and transform.",schedule:"Monday · 8:15pm–9:30pm",description:"VoxAtma welcomes adults with or without musical experience. It is a space to develop the voice, sing varied repertoire, reduce stress and transform individual experience through regular artistic practice.",benefits:[["Wellbeing","Breathing and collective singing create focus, energy and balance."],["Learning","Music reading is not required: the journey is guided step by step."],["Transformation","Every voice helps transform the sound and the community."]]},
  voxcor:{range:"Adults",tag:"Adult choir · Vocal group",lead:"Choral repertoire, artistic commitment and community.",schedule:"According to season",description:"VoxCor brings adult voices together through repertoire, technique, interpretation and performance, combining musical commitment with the community spirit of VoxLaci.",benefits:[["Repertoire","Music from different periods, styles and geographies."],["Interpretation","Phrasing, text, ensemble sound and stage presence."],["Concerts","Participation in VoxLaci projects, festivals and concerts."]]},
  tutti:{range:"All voices",tag:"Collective singing · Group singing",lead:"A group for singing, connecting people and transforming community.",schedule:"According to project",description:"Tutti is collective singing at its most direct: an accessible space where group experience, listening and the joy of making music together are central.",benefits:[["Welcome","An entry point for anyone starting or returning to singing."],["Connection","Music as a way to meet people and build relationships."],["Expression","Discovering the possibilities of the voice without pressure or labels."]]},
  intuicao:{range:"Female voices",tag:"Vocal ensemble",lead:"The colour, strength and intimacy of female voices.",schedule:"By audition and project",description:"Intuição explores repertoire for female voices, focusing on blend, vocal independence and interpretation.",benefits:[["Sound","Balance, tuning and timbral identity."],["Repertoire","Female choral music from different traditions."],["Ensemble","Close and committed work between singers."]]},
  hirmandade:{range:"Male voices · 15+",tag:"Male vocal ensemble",lead:"Fraternity, presence and repertoire for male voices.",schedule:"Monday · 8:30pm–11pm",description:"Hirmandade brings male singers aged 15+ together in an ensemble devoted to technique, repertoire and building a shared sound.",benefits:[["Fraternity","Human connection supports the musical work."],["Technique","Developing the different male vocal ranges."],["Stage","Projects and performances with a distinct identity."]]},
  quorum:{range:"Chamber choir",tag:"Chamber Choir",lead:"Precision, listening and chamber repertoire.",schedule:"By audition",description:"Qūórum is a chamber choir for experienced singers, focused on repertoire requiring independence, reading, tuning and refined ensemble quality.",benefits:[["Chamber","Few voices, strong individual responsibility."],["Precision","Tuning, balance, diction and style."],["Repertoire","Artistically demanding programmes."]]},
  kyma:{range:"Advanced",tag:"Vocal Ensemble Pro",lead:"Wave, movement and highly committed vocal creation.",schedule:"By audition or invitation",description:"KYMA is VoxLaci's professionally oriented path for singers with solid preparation and availability for demanding projects.",benefits:[["Excellence","Individual preparation and ensemble precision."],["Creation","Challenging repertoire and new vocal languages."],["Projection","Projects designed for professional contexts."]]},
  voxpetrus:{range:"Liturgical",tag:"Ceremonies · Sacred music",lead:"Liturgical music for celebrations and meaningful moments.",schedule:"By ceremony or project",description:"Vox Petrus offers repertoire and ensembles suited to masses, weddings, baptisms, memorials and other liturgical settings.",benefits:[["Sacred repertoire","Music selected for each celebration."],["Ensembles","Vocal and instrumental solutions adapted to the space."],["Guidance","Programme preparation in dialogue with each family or organisation."]]}
};
const key = document.body.dataset.ensemble;
const pageLanguage = document.body.dataset.language || "pt";
const data = pageLanguage === "en" ? {...ensemblePages[key],...ensembleEnglish[key]} : ensemblePages[key];
if (data) {
  document.title = `${data.name} | Coro e grupo vocal VoxLaci em Cascais`;
  document.querySelectorAll("[data-name]").forEach(x=>x.textContent=data.name);
  document.querySelectorAll("[data-tag]").forEach(x=>x.textContent=data.tag);
  document.querySelectorAll("[data-range]").forEach(x=>x.textContent=data.range);
  document.querySelectorAll("[data-lead]").forEach(x=>x.textContent=data.lead);
  document.querySelectorAll("[data-schedule]").forEach(x=>x.textContent=data.schedule);
  document.querySelectorAll("[data-description]").forEach(x=>x.textContent=data.description);
  const imagePath = pageLanguage === "en" ? data.image.replace("../assets/","../../assets/") : data.image;
  const hero=document.querySelector("[data-image]"); if(hero){hero.src=imagePath;hero.alt=`${data.name}, VoxLaci choir and vocal group in Cascais`;}
  const benefits=document.querySelector("[data-benefits]");
  if(benefits) benefits.innerHTML=data.benefits.map(([h,p],i)=>`<article><span class="eyebrow">0${i+1}</span><h3>${h}</h3><p>${p}</p></article>`).join("");
}
