# -*- coding: utf-8 -*-
from __future__ import annotations

from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
LANGS = ["pt", "en", "es", "fr", "it", "zh"]

UI = {
    "pt": {"events": "Eventos", "overview": "Visão geral", "archive": "Arquivo recuperado", "history": "História e contexto", "program": "Programa e informações", "audience": "Destinatários", "open": "Abrir evento", "back": "Voltar aos eventos", "casting": "Fazer casting online", "update": "Informação em atualização.", "subtitle": "Festivais, concertos, encontros, formação e experiências criadas pela VoxLaci em Cascais, em Lisboa, em Portugal e no mundo.", "cta": "O próximo evento pode começar com a sua voz.", "sources": "Ficheiros de origem"},
    "en": {"events": "Events", "overview": "Overview", "archive": "Recovered archive", "history": "History and context", "program": "Programme / information", "audience": "Audience", "open": "Open event", "back": "Back to events", "casting": "Online casting", "update": "Information being updated.", "subtitle": "Festivals, concerts, gatherings, training and experiences created by VoxLaci in Cascais, Lisbon, Portugal and worldwide.", "cta": "The next event can begin with your voice.", "sources": "Source files"},
    "es": {"events": "Eventos", "overview": "Visión general", "archive": "Archivo recuperado", "history": "Historia y contexto", "program": "Programa / información", "audience": "Destinatarios", "open": "Abrir evento", "back": "Volver a eventos", "casting": "Casting online", "update": "Información en actualización.", "subtitle": "Festivales, conciertos, encuentros, formación y experiencias creadas por VoxLaci en Cascais, Lisboa, Portugal y el mundo.", "cta": "El próximo evento puede empezar con tu voz.", "sources": "Archivos de origen"},
    "fr": {"events": "Événements", "overview": "Vue d’ensemble", "archive": "Archive récupérée", "history": "Histoire et contexte", "program": "Programme / information", "audience": "Publics", "open": "Ouvrir l’événement", "back": "Retour aux événements", "casting": "Casting en ligne", "update": "Information en cours de mise à jour.", "subtitle": "Festivals, concerts, rencontres, formation et expériences créés par VoxLaci à Cascais, Lisbonne, au Portugal et dans le monde.", "cta": "Le prochain événement peut commencer avec votre voix.", "sources": "Fichiers source"},
    "it": {"events": "Eventi", "overview": "Visione generale", "archive": "Archivio recuperato", "history": "Storia e contesto", "program": "Programma / informazioni", "audience": "Destinatari", "open": "Apri evento", "back": "Torna agli eventi", "casting": "Casting online", "update": "Informazioni in aggiornamento.", "subtitle": "Festival, concerti, incontri, formazione ed esperienze create da VoxLaci a Cascais, Lisbona, in Portogallo e nel mondo.", "cta": "Il prossimo evento può iniziare con la tua voce.", "sources": "File sorgente"},
    "zh": {"events": "活动", "overview": "概览", "archive": "已恢复档案", "history": "历史与背景", "program": "节目 / 信息", "audience": "对象", "open": "打开活动", "back": "返回活动", "casting": "在线试唱", "update": "信息更新中。", "subtitle": "VoxLaci 在卡斯凯什、里斯本、葡萄牙和世界各地创建的节日、音乐会、相遇、培训和体验。", "cta": "下一场活动可以从你的声音开始。", "sources": "来源文件"},
}

EVENTS = [
    {"slug":"janeiras","title":"Janeiras","category":"Tradição · Janeiro","image":"/assets/event-janeiras.jpg","old":["/eventos/janeiras/"],"sources":["eventos/janeiras/index.html","eventos/agenda/index.html"],"summary":{"pt":"Celebrar a tradição das Janeiras e começar o ano a cantar em comunidade.","en":"Singing tradition and beginning the year together.","es":"Cantar la tradición y comenzar el año en comunidad.","fr":"Chanter la tradition et commencer l’année ensemble.","it":"Cantare la tradizione e iniziare l’anno in comunità.","zh":"唱响传统，在社区中开启新年。"},"history":["Evento associado à tradição das Janeiras e ao arranque do ano em comunidade.","A agenda recuperada inclui referências a concertos de Janeiras e a eventos realizados em janeiro."],"program":["Informação histórica recuperada sobretudo a partir da agenda.","Informação em atualização."],"audience":["Comunidade VoxLaci.","Público local e famílias."]},
    {"slug":"ramos","title":"RAMOS · Palm Sunday Festival","category":"Festival internacional","image":"/assets/ramos/felicia-barber-2027.jpg","old":["/ramos/","/eventos/ramos-palm-sunday-festival/"],"sources":["ramos/index.html","ramos/arquivo-completo/index.html","ramos-edition.js"],"summary":{"pt":"Festival internacional de música coral sacra, criado em 2005, com maestros convidados, ensaios intensivos e concertos.","en":"International sacred choral music festival created in 2005, with guest conductors, intensive rehearsals and concerts.","es":"Festival internacional de música coral sacra creado en 2005, con directores invitados, ensayos intensivos y conciertos.","fr":"Festival international de musique chorale sacrée créé en 2005, avec chefs invités, répétitions intensives et concerts.","it":"Festival internazionale di musica corale sacra creato nel 2005, con direttori ospiti, prove intensive e concerti.","zh":"2005 年创立的国际圣乐合唱节，包含客座指挥、密集排练和音乐会。"},"history":["Desde 2005, o RAMOS traz a Portugal maestros internacionais e cantores ligados à música coral sacra.","A página principal do RAMOS contém um arquivo próprio com edições, cartazes, maestros, programas e repertórios."],"program":["Edição de 2027 anunciada: XIX Palm Sunday Festival, 15 a 21 de março de 2027, com Felicia Barber (EUA).","Consulte o arquivo principal para conhecer todas as edições e repertórios."],"audience":["Cantores com experiência.","Público de música coral sacra.","Maestros e comunidade coral internacional."],"links":[("Arquivo RAMOS","/ramos/")]},
    {"slug":"voxpueri-festival","title":"VoxPueri Festival","category":"Festival infantil","image":"/assets/event-puerifest.jpg","old":["/eventos/voxpueri-fest/"],"sources":["eventos/voxpueri-fest/index.html"],"summary":{"pt":"Semana de atividades para crianças durante as férias da Páscoa, com música de manhã e desporto à tarde.","en":"Activity week for children during Easter holidays, with music in the mornings and sports in the afternoons.","es":"Semana de actividades para niños en vacaciones de Pascua, con música por la mañana y deporte por la tarde.","fr":"Semaine d’activités pour enfants pendant les vacances de Pâques, avec musique le matin et sport l’après-midi.","it":"Settimana di attività per bambini durante le vacanze di Pasqua, con musica al mattino e sport al pomeriggio.","zh":"复活节假期儿童活动周，上午音乐，下午运动。"},"history":["7.ª edição recuperada: 6 a 9 de abril, de Segunda a Quinta-Feira Santa, das 9h às 17h, com possibilidade de prolongamento até às 19h.","Decorreu na Fundação O Século, em São Pedro do Estoril."],"program":["Música de manhã e desporto à tarde.","Oficinas de expressão artística com técnicas de canto coral.","Aulas de surf, jogos e outras atividades.","Concerto final no último dia."],"audience":["Crianças dos 6 aos 12 anos.","Possibilidade de participação de crianças entre os 4 e os 6 anos, quando tenham um irmão participante."]},
    {"slug":"reis","title":"Reis","category":"Tradição · Epifania","image":"/assets/event-reis.jpg","old":["/eventos/reis/"],"sources":["eventos/reis/index.html"],"summary":{"pt":"Evento coral em torno do Dia de Reis, ligado à origem simbólica do percurso da VoxLaci.","en":"Choral event around Epiphany, connected to the symbolic origin of the VoxLaci journey.","es":"Evento coral en torno al Día de Reyes, ligado al origen simbólico del camino VoxLaci.","fr":"Événement choral autour de l’Épiphanie, lié à l’origine symbolique du parcours VoxLaci.","it":"Evento corale intorno all’Epifania, legato all’origine simbolica del percorso VoxLaci.","zh":"围绕主显节的合唱活动，与 VoxLaci 旅程的象征性起点相连。"},"history":["Foi num 6 de janeiro, em Verona, que Myguel Santos e Castro tomou consciência de que queria trabalhar com coros.","O arquivo refere 24 anos consecutivos a celebrar o Dia de Reis."],"program":["Tradição que assinala o final dos eventos de Natal.","Já teve nomes como Concerto de Reis, Grande Concerto de Reis e Concerto VoxLaci de Reis."],"audience":["Comunidade VoxLaci.","Público de Cascais e São Domingos de Rana."]},
    {"slug":"stella","title":"STELLA","category":"Natal · luz · comunidade","image":"/assets/event-stella.jpg","old":["/eventos/stella/"],"sources":["eventos/stella/index.html"],"summary":{"pt":"Festival VoxLaci antes do Natal, criado para convidar diferentes religiões e comunidades a partilharem o seu modo de viver o Natal.","en":"VoxLaci event/festival before Christmas, inviting religions and communities to share their way of living Christmas.","es":"Evento/festival VoxLaci antes de Navidad, invitando a religiones y comunidades a compartir su forma de vivir la Navidad.","fr":"Événement/festival VoxLaci avant Noël, invitant religions et communautés à partager leur manière de vivre Noël.","it":"Evento/festival VoxLaci prima di Natale, invitando religioni e comunità a condividere il proprio modo di vivere il Natale.","zh":"VoxLaci 圣诞前活动/节日，邀请不同宗教和社区分享他们体验圣诞的方式。"},"history":["Nasceu da vontade de convidar várias religiões e comunidades a viverem o Natal através da voz, da luz e da partilha.","Do arquivo: “De Cascais, com Cascais, para Cascais e para todo o mundo.”"],"program":["Voz, luz, comunidade e partilha inter-religiosa e intercultural.","Informação em atualização."],"audience":["Comunidades religiosas e culturais.","Público de Cascais e comunidade VoxLaci."]},
    {"slug":"gratias","title":"Gratias","category":"Gratidão","image":"/assets/event-gratias.jpg","old":["/gratias/"],"sources":["gratias/index.html"],"summary":{"pt":"Música como gesto de gratidão, encontro e partilha.","en":"Music as an act of gratitude, connection and sharing.","es":"Música como gesto de gratitud, encuentro y compartir.","fr":"La musique comme geste de gratitude, de rencontre et de partage.","it":"La musica come gesto di gratitudine, incontro e condivisione.","zh":"音乐作为感恩、相遇与分享的姿态。"},"history":["Página recuperada no arquivo VoxLaci com o título Gratias."],"program":["Informação em atualização."],"audience":["Comunidade VoxLaci.","Público local."]},
    {"slug":"deuses","title":"Deuses","category":"Criação coral","image":"/assets/event-deuses.jpg","old":["/eventos/"],"sources":["index.html","script.js"],"summary":{"pt":"Criação coral, narrativa e espetáculo apresentada no site como evento VoxLaci.","en":"Choral creation, narrative and performance presented on the site as a VoxLaci event.","es":"Creación coral, narrativa y espectáculo presentada en el sitio como evento VoxLaci.","fr":"Création chorale, récit et spectacle présenté sur le site comme événement VoxLaci.","it":"Creazione corale, narrazione e spettacolo presentati nel sito come evento VoxLaci.","zh":"网站中作为 VoxLaci 活动呈现的合唱创作、叙事与演出。"},"history":["A página principal apresenta Deuses como criação coral, narrativa e espetáculo."],"program":["Informação em atualização."],"audience":["Público geral.","Comunidade VoxLaci."]},
    {"slug":"barbershop-college","title":"Barbershop College","category":"Formação · harmonia","image":"/assets/event-barbershop.jpg","old":["/barbershop/"],"sources":["barbershop/index.html"],"summary":{"pt":"Evento de formação e prática em barbershop, com sessões de trabalho, performances, quartetos e convidados internacionais.","en":"Training and practice event in barbershop, with sessions, performances, quartets and international guests.","es":"Evento de formación y práctica de barbershop, con sesiones, actuaciones, cuartetos e invitados internacionales.","fr":"Événement de formation et pratique barbershop, avec sessions, performances, quartets et invités internationaux.","it":"Evento di formazione e pratica barbershop, con sessioni, performance, quartetti e ospiti internazionali.","zh":"理发店四重唱风格的培训与实践活动，包含课程、演出、四重唱和国际嘉宾。"},"history":["Arquivo extenso com edições de 2022 e 2023, bilhetes, alojamento, sessões educativas e convidados.","Referências recuperadas a The Hanfris Quartet, Steve Scott, Kara Martin, Sara Santos, Sara Almeida, Myguel Santos e Castro e Miguel Fernandes."],"program":["Harmony College com diferentes tipos de bilhete.","Sessões de aquecimento, coaching under glass, scratch quartets e temas sobre liderança, voz, interpretação e organização coral."],"audience":["Cantores e quartetos.","Pessoas interessadas em barbershop e harmonia vocal."]},
    {"slug":"dia-mundial-da-musica","title":"Dia Mundial da Música","category":"1 de outubro","image":"/assets/event-worldmusic.jpg","old":["/eventos/#musica"],"sources":["index.html","eventos/index.html"],"summary":{"pt":"Celebração da música como linguagem universal.","en":"Celebration of music as a universal language.","es":"Celebración de la música como lenguaje universal.","fr":"Célébration de la musique comme langage universel.","it":"Celebrazione della musica come linguaggio universale.","zh":"庆祝音乐作为世界语言。"},"history":["A página principal e a página de eventos apresentam o Dia Mundial da Música como celebração da música enquanto linguagem universal."],"program":["Informação em atualização."],"audience":["Comunidade VoxLaci.","Público geral."]},
    {"slug":"voxaround","title":"VoxAround","category":"Intercâmbio","image":"/assets/event-voxaround.jpg","old":["/eventos/voxaround/"],"sources":["eventos/voxaround/index.html"],"summary":{"pt":"Projeto de circulação que liga vozes, cidades e culturas.","en":"Circulation event/project connecting voices, cities and cultures.","es":"Evento/proyecto de circulación que conecta voces, ciudades y culturas.","fr":"Événement/projet de circulation reliant voix, villes et cultures.","it":"Evento/progetto di circolazione che collega voci, città e culture.","zh":"连接声音、城市与文化的流动项目/活动。"},"history":["A página recuperada indica apenas: “Informações disponíveis brevemente.”"],"program":["Informação em atualização."],"audience":["Cantores.","Comunidade internacional."]},
    {"slug":"conductors-mob","title":"Conductor’s MOB","category":"Maestros","image":"/assets/event-conductors.jpg","old":["/eventos/conductors-mob/"],"sources":["eventos/conductors-mob/index.html"],"summary":{"pt":"Encontro de desenvolvimento para maestros e estudantes de direção.","en":"Gathering and development for conductors.","es":"Encuentro y desarrollo para directores.","fr":"Rencontre et développement pour chefs.","it":"Incontro e sviluppo per direttori.","zh":"面向指挥的相遇与发展。"},"history":["A página recuperada indica apenas: “Informações disponíveis brevemente.”"],"program":["Informação em atualização."],"audience":["Maestros, maestras e estudantes de direção."]},
    {"slug":"voxpop","title":"voX±Pop","category":"Eventos internacionais","image":"/legacy-media/3e18580f3c59.jpg","old":["/voxpop/","/cascaisvoxpop/","/lisboavoxpop/","/portovoxpop/","/monopolivoxpop/","/londonvoxpop/","/dakarvoxpop/"],"sources":["voxpop/index.html","cascaisvoxpop/index.html","lisboavoxpop/index.html","portovoxpop/index.html","monopolivoxpop/index.html","londonvoxpop/index.html","dakarvoxpop/index.html"],"summary":{"pt":"Conceito internacional de eventos corais de três dias em cidades à escala de quem caminha: Cascais, Lisboa, Porto, Londres, Monopoli e Dakar.","en":"International concept of 3-day choral events in walkable cities: Cascais, Lisbon, Porto, London, Monopoli and Dakar.","es":"Concepto internacional de eventos corales de 3 días en ciudades caminables: Cascais, Lisboa, Porto, London, Monopoli y Dakar.","fr":"Concept international d’événements choraux de 3 jours dans des villes accessibles à pied : Cascais, Lisbonne, Porto, London, Monopoli et Dakar.","it":"Concetto internazionale di eventi corali di 3 giorni in città percorribili a piedi: Cascais, Lisbona, Porto, London, Monopoli e Dakar.","zh":"在适合步行的城市举办的三天国际合唱活动：卡斯凯什、里斯本、波尔图、伦敦、莫诺波利和达喀尔。"},"history":["O arquivo apresenta a frase: “Bring your VOX and POP in the experience.”","O conceito propõe três dias de música numa cidade ou vila à escala de quem caminha, com taxa base de participação de 99€ por pessoa."],"program":["Participação com coro, com ensemble criado para o evento, com amigos, individualmente ou através de workshops.","Cidades recuperadas: Cascais, Lisboa, Porto, Londres, Monopoli e Dakar."],"audience":["Coros.","Cantores individuais.","Amigos e participantes internacionais."],"links":[("Cascais","/cascaisvoxpop/"),("Lisboa","/lisboavoxpop/"),("Porto","/portovoxpop/"),("Monopoli","/monopolivoxpop/"),("Londres","/londonvoxpop/"),("Dakar","/dakarvoxpop/")]},
    {"slug":"dakar-singing-festival","title":"Dakar Singing Festival","category":"Internacional · viagem RAMOS","image":"/legacy-media/2d6d25edea61.jpg","old":["/dakar-singing-festival/"],"sources":["dakar-singing-festival/index.html"],"summary":{"pt":"Evento internacional para cantores com experiência, apresentado como viagem RAMOS.","en":"International event for experienced singers, presented as a RAMOS journey.","es":"Evento internacional para cantantes con experiencia, presentado como viaje RAMOS.","fr":"Événement international pour chanteurs expérimentés, présenté comme voyage RAMOS.","it":"Evento internazionale per cantanti esperti, presentato come viaggio RAMOS.","zh":"面向有经验歌者的国际活动，作为 RAMOS 旅程呈现。"},"history":["O arquivo apresenta o evento como “Bem-vindos à viagem do RAMOS / Welcome to RAMOS Journey”.","Inclui sinopse do RAMOS, ensaios, concertos, chegada e partida, direção artística e repertório RAMOS 2022."],"program":["Ensaios recuperados: domingo, 3 de abril; segunda, terça e quarta-feira, 4, 5 e 6 de abril; quinta-feira livre.","Concertos recuperados: sexta-feira, 8 de abril; sábado, 9 de abril; Domingo de Ramos, 10 de abril.","Repertório RAMOS 2022: Of Love, Life and Spirit."],"audience":["Cantores com experiência.","Coros em viagem."]},
    {"slug":"musica-de-segunda","title":"Música de Segunda","category":"Série de música","image":"/assets/event-worldmusic.jpg","old":["/eventos/"],"sources":["index.html","script.js"],"summary":{"pt":"Série apresentada no site como encontro regular com música, artistas e comunidade.","en":"Music series presented on the site as a regular meeting with music, artists and community.","es":"Serie musical presentada en el sitio como encuentro regular con música, artistas y comunidad.","fr":"Série musicale présentée sur le site comme rencontre régulière avec musique, artistes et communauté.","it":"Serie musicale presentata nel sito come incontro regolare con musica, artisti e comunità.","zh":"网站中呈现为音乐、艺术家和社区定期相遇的音乐系列。"},"history":["A página principal apresenta Música de Segunda como série de música."],"program":["Informação em atualização."],"audience":["Público geral.","Comunidade VoxLaci."]},
    {"slug":"agenda","title":"Agenda","category":"Arquivo cronológico","image":"/assets/hero-live.jpg","old":["/eventos/agenda/"],"sources":["eventos/agenda/index.html"],"summary":{"pt":"Arquivo cronológico recuperado com eventos, concertos, viagens, festivais e atuações.","en":"Recovered chronological archive with events, concerts, tours, festivals and performances.","es":"Archivo cronológico recuperado con eventos, conciertos, viajes, festivales y actuaciones.","fr":"Archive chronologique récupérée avec événements, concerts, voyages, festivals et performances.","it":"Archivio cronologico recuperato con eventi, concerti, viaggi, festival e performance.","zh":"已恢复的时间档案，包含活动、音乐会、旅行、节日和演出。"},"history":["A agenda recuperada contém referências a 2018 e a anos anteriores, com datas, locais, coros e preços."],"program":["Inclui Concerto de Reis, Ciclo de Concertos de Ramos, On Stage, Música ao Domingo de Manhã, Aldeia em Festa, viagens, workshops e concertos de Natal."],"audience":["Arquivo interno.","Público que procura o histórico de eventos VoxLaci."]},
]

def attrs(texts):
    return " ".join(f"data-{lang}={json.dumps(texts.get(lang, texts.get('pt','')))}" for lang in LANGS)
def ui(key):
    return attrs({lang:UI[lang][key] for lang in LANGS})
def lis(items):
    if not items:
        return f'<p class="muted" {ui("update")}>{UI["pt"]["update"]}</p>'
    return "<ul>" + "".join(f"<li>{escape(x)}</li>" for x in items) + "</ul>"
def img(src,title):
    return f'<img src="{escape(src)}" alt="{escape(title)}" loading="lazy">'
def source_count_label(count):
    return f"{count} ficheiro" if count == 1 else f"{count} ficheiros"
def head(title, desc, url, image, schema_extra=""):
    org = {"@context":"https://schema.org","@type":["Organization","PerformingGroup"],"name":"VoxLaci","url":"https://voxlaci.com/","email":"info@voxlaci.com","telephone":"+351925075186","sameAs":["https://www.facebook.com/VoxLaci","https://www.instagram.com/VoxLaci","https://www.youtube.com/@VoxLaci"]}
    return f'''<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | VoxLaci</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="https://voxlaci.com{url}"><meta property="og:title" content="{escape(title)} | VoxLaci"><meta property="og:description" content="{escape(desc)}"><meta property="og:image" content="https://voxlaci.com{escape(image)}"><meta property="og:type" content="website">
<link rel="stylesheet" href="/subpage.css"><link rel="stylesheet" href="/universal-share.css?v=14"><script type="application/ld+json">{json.dumps(org, ensure_ascii=False)}</script>{schema_extra}</head>'''
def header():
    buttons = "".join(f'<button type="button" data-set-lang="{l}">{l.upper()}</button>' for l in LANGS)
    return f'''<body><header class="page-nav"><a href="/"><img src="/assets/voxlaci-logo-white.png" alt="VoxLaci"></a><nav><a href="/#vozes">Ensembles</a><a href="/projetos/">Projetos</a><a href="/eventos/">Eventos</a><a href="/#servicos">Serviços</a></nav><div class="project-lang" aria-label="Idiomas">{buttons}</div><a class="cta" href="/#inscricao">{UI["pt"]["casting"]}</a></header>'''
def footer():
    return '''<footer class="page-footer"><div><img src="/assets/voxlaci-logo-white.png" alt="VoxLaci"></div><div><a href="mailto:info@voxlaci.com">info@voxlaci.com</a><a href="/">Voltar ao site</a></div></footer><script src="/project-language.js" defer></script><script src="/universal-share.js?v=14" defer></script></body></html>'''
def event_schema(e):
    data = {"@context":"https://schema.org","@type":["Event","CreativeWork"],"name":e["title"],"description":e["summary"]["pt"],"url":f"https://voxlaci.com/eventos/{e['slug']}/","image":f"https://voxlaci.com{e['image']}","organizer":{"@type":"Organization","name":"VoxLaci","url":"https://voxlaci.com/"},"eventStatus":"https://schema.org/EventScheduled","eventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode","location":{"@type":"Place","name":"VoxLaci / Cascais / Portugal"}}
    bread = {"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"VoxLaci","item":"https://voxlaci.com/"},{"@type":"ListItem","position":2,"name":"Eventos","item":"https://voxlaci.com/eventos/"},{"@type":"ListItem","position":3,"name":e["title"],"item":f"https://voxlaci.com/eventos/{e['slug']}/"}]}
    return f'<script type="application/ld+json">{json.dumps(data, ensure_ascii=False)}</script><script type="application/ld+json">{json.dumps(bread, ensure_ascii=False)}</script>'
def render_event(e):
    links = "".join(f'<a href="{href}">{escape(label)} <span>→</span></a>' for label,href in e.get("links",[]))
    if not links:
        links = "".join(f'<a href="{x}">{escape(x)} <span>→</span></a>' for x in e["old"])
    sources = "".join(f"<li>{escape(x)}</li>" for x in e["sources"])
    return head(e["title"], e["summary"]["pt"], f"/eventos/{e['slug']}/", e["image"], event_schema(e)) + header() + f'''<main>
<section class="page-hero project-hero"><img src="{escape(e["image"])}" alt="{escape(e["title"])}"><div class="page-hero-copy"><p class="eyebrow">{escape(e["category"])}</p><h1>{escape(e["title"])}</h1><p {attrs(e["summary"])}>{escape(e["summary"]["pt"])}</p><div class="page-hero-actions"><a class="button primary" href="#arquivo" {ui("archive")}>{UI["pt"]["archive"]}</a><a class="button" href="/eventos/" {ui("back")}>{UI["pt"]["back"]}</a></div></div></section>
<section class="intro"><div><p class="eyebrow" {ui("overview")}>{UI["pt"]["overview"]}</p><h2>{escape(e["title"])}</h2></div><div class="intro-copy"><p {attrs(e["summary"])}>{escape(e["summary"]["pt"])}</p><div class="fact-grid"><div><b>Categoria</b><span>{escape(e["category"])}</span></div><div><b>Arquivo</b><span>{source_count_label(len(e["sources"]))}</span></div><div><b>URL</b><span>/eventos/{escape(e["slug"])}/</span></div></div></div></section>
<section class="section white"><div class="benefits"><article><h3 {ui("history")}>{UI["pt"]["history"]}</h3>{lis(e["history"])}</article><article><h3 {ui("program")}>{UI["pt"]["program"]}</h3>{lis(e["program"])}</article><article><h3 {ui("audience")}>{UI["pt"]["audience"]}</h3>{lis(e["audience"])}</article></div></section>
<section class="section" id="arquivo"><div class="section-head"><p class="eyebrow" {ui("archive")}>{UI["pt"]["archive"]}</p><h2>{escape(e["title"])}</h2></div><div class="accordion"><details open><summary>Ligações e URLs antigas</summary><div class="ensemble-list">{links}</div></details><details><summary {ui("sources")}>{UI["pt"]["sources"]}</summary><div><ul>{sources}</ul></div></details></div></section>
<section class="section white"><div class="legacy-gallery">{img(e["image"], e["title"])}</div></section><section class="page-cta"><p class="eyebrow">VoxLaci</p><h2 {ui("cta")}>{UI["pt"]["cta"]}</h2><a class="button primary" href="/#inscricao" {ui("casting")}>{UI["pt"]["casting"]}</a></section></main>''' + footer()
def render_index():
    collection = {"@context":"https://schema.org","@type":"CollectionPage","name":"Eventos VoxLaci","description":UI["pt"]["subtitle"],"url":"https://voxlaci.com/eventos/","hasPart":[{"@type":"Event","name":e["title"],"url":f"https://voxlaci.com/eventos/{e['slug']}/"} for e in EVENTS]}
    cards = "".join(f'''<a class="edition-card project-directory-card" href="/eventos/{escape(e["slug"])}/">{img(e["image"],e["title"])}<span>{i:02d} · {escape(e["category"])}</span><h3>{escape(e["title"])}</h3><p {attrs(e["summary"])}>{escape(e["summary"]["pt"])}</p><b {ui("open")}>{UI["pt"]["open"]} →</b></a>''' for i,e in enumerate(EVENTS,1))
    schema = f'<script type="application/ld+json">{json.dumps(collection, ensure_ascii=False)}</script>'
    return head("Eventos VoxLaci", UI["pt"]["subtitle"], "/eventos/", "/assets/event-worldmusic.jpg", schema) + header() + f'''<main><section class="page-hero project-hero"><img src="/assets/event-worldmusic.jpg" alt="Eventos VoxLaci"><div class="page-hero-copy"><p class="eyebrow">VoxLaci</p><h1 {ui("events")}>{UI["pt"]["events"]}</h1><p {attrs({l:UI[l]["subtitle"] for l in LANGS})}>{UI["pt"]["subtitle"]}</p></div></section><section class="intro"><div><p class="eyebrow" {ui("overview")}>{UI["pt"]["overview"]}</p><h2>Eventos que transformam comunidades.</h2></div><div class="intro-copy"><p>Este arquivo reorganiza a memória histórica dos eventos VoxLaci: festivais, concertos, encontros internacionais, formação, tradições e experiências criadas para ligar pessoas através da voz.</p><div class="fact-grid"><div><b>Eventos</b><span>{len(EVENTS)}</span></div><div><b>Arquivo</b><span>Eventos, RAMOS, voX±Pop e páginas antigas</span></div><div><b>Idiomas</b><span>PT · EN · ES · FR · IT · ZH</span></div></div></div></section><section class="section white"><div class="section-head"><p class="eyebrow" {ui("events")}>{UI["pt"]["events"]}</p><h2>Arquivo vivo de eventos</h2></div><div class="edition-grid project-directory">{cards}</div></section><section class="page-cta"><p class="eyebrow">VoxLaci</p><h2 {ui("cta")}>{UI["pt"]["cta"]}</h2><a class="button primary" href="/#inscricao" {ui("casting")}>{UI["pt"]["casting"]}</a></section></main>''' + footer()

def main():
    (ROOT / "eventos").mkdir(exist_ok=True)
    (ROOT / "eventos/index.html").write_text(render_index(), encoding="utf-8")
    for e in EVENTS:
        p = ROOT / "eventos" / e["slug"]
        p.mkdir(exist_ok=True)
        (p / "index.html").write_text(render_event(e), encoding="utf-8")

if __name__ == "__main__":
    main()
